version: '2'
services:
  database:
    image: mrigor/hsqldb
    ports:
      - "9001:9001"
    volumes:
      - ./db/schema.sql:/schema.sql
      - ./db/data.sql:/data.sql
      - ./db/sqltool.rc:/root/sqltool.rc
    network_mode: "host"
    command: bash -c "nohup java -cp /lib/hsqldb.jar org.hsqldb.server.Server --database.0 file:/data/db --dbname.0 db & java -jar /lib/sqltool.jar --autoCommit db /schema.sql /data.sql && tail -f /dev/null"
  rest:
    image: openjdk:alpine
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=database
    volumes:
      - ./server-rest/target/server-rest-1.0-SNAPSHOT.jar:/rest.jar
    network_mode: "host"
    depends_on:
      - database
    command: java -jar /rest.jar
  web:
    image: openjdk:alpine
    ports:
      - "8081:8081"
    environment:
      - REST_HOST=rest
    volumes:
      - ./server-web/target/server-web-1.0-SNAPSHOT.jar:/web.jar
    network_mode: "host"
    depends_on:
      - rest
    command: java -jar /web.jar