version: '2'
services:
  database:
    image: mrigor/hsqldb
    ports:
      - "9001:9001"
    volumes:
      - ./schema.sql:/schema.sql
      - ./data.sql:/data.sql
      - ./sqltool.rc:/root/sqltool.rc
    command: bash -c "nohup java -cp /lib/hsqldb.jar org.hsqldb.server.Server --database.0 file:/data/db --dbname.0 db & java -jar /lib/sqltool.jar --autoCommit db /schema.sql /data.sql && tail -f /dev/null"
  rest:
    image: openjdk:alpine
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=database
    links:
      - database
    volumes:
      - ./target/server-rest-1.0-SNAPSHOT.jar:/app.jar
    command: java -jar /app.jar